version: '3.8'

services:


  app:
    build:
      context: ./project
      dockerfile: App.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - secret=VG5aT1MyZ1FPdGJxY2c2NWFQeWp0dmNzOHdUdUduREw=

  front:
    build:
      context: ./ems-frontend
      dockerfile: Front.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app


