version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - secret=VG5aT1MyZ1FPdGJxY2c2NWFQeWp0dmNzOHdUdUduREw=
      - user=root
      - password=1234
      - database=IETI-Project
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=IETI-Project
